export default {
    data: [
        {
            id: 858450,
            date: '2023-03-23T00:00:00.000Z',
            home_team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            home_team_score: 114,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            visitor_team_score: 116,
            dateObj: false,
        },
        {
            id: 858447,
            date: '2023-03-23T00:00:00.000Z',
            home_team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            home_team_score: 111,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            visitor_team_score: 106,
            dateObj: false,
        },
        {
            id: 858449,
            date: '2023-03-23T00:00:00.000Z',
            home_team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            home_team_score: 127,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            visitor_team_score: 105,
            dateObj: false,
        },
        {
            id: 858448,
            date: '2023-03-23T00:00:00.000Z',
            home_team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            home_team_score: 115,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            visitor_team_score: 96,
            dateObj: false,
        },
    ],
};
