export const dayEight = {
    data: [
        {
            id: 858466,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 16,
                abbreviation: 'MIA',
                city: 'Miami',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Miami Heat',
                name: 'Heat',
            },
            home_team_score: 0,
            period: 0,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            visitor_team_score: 129,
        },
        {
            id: 858461,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 1,
                abbreviation: 'ATL',
                city: 'Atlanta',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Atlanta Hawks',
                name: 'Hawks',
            },
            home_team_score: 143,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 12,
                abbreviation: 'IND',
                city: 'Indiana',
                conference: 'East',
                division: 'Central',
                full_name: 'Indiana Pacers',
                name: 'Pacers',
            },
            visitor_team_score: 130,
        },
        {
            id: 858464,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            home_team_score: 110,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            visitor_team_score: 131,
        },
        {
            id: 858463,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 8,
                abbreviation: 'DEN',
                city: 'Denver',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Denver Nuggets',
                name: 'Nuggets',
            },
            home_team_score: 129,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 17,
                abbreviation: 'MIL',
                city: 'Milwaukee',
                conference: 'East',
                division: 'Central',
                full_name: 'Milwaukee Bucks',
                name: 'Bucks',
            },
            visitor_team_score: 106,
        },
        {
            id: 858465,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 26,
                abbreviation: 'SAC',
                city: 'Sacramento',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Sacramento Kings',
                name: 'Kings',
            },
            home_team_score: 121,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 29,
                abbreviation: 'UTA',
                city: 'Utah',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Utah Jazz',
                name: 'Jazz',
            },
            visitor_team_score: 113,
        },
        {
            id: 858462,
            date: '2023-03-25T00:00:00.000Z',
            home_team: {
                id: 24,
                abbreviation: 'PHX',
                city: 'Phoenix',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Phoenix Suns',
                name: 'Suns',
            },
            home_team_score: 125,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 23,
                abbreviation: 'PHI',
                city: 'Philadelphia',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Philadelphia 76ers',
                name: '76ers',
            },
            visitor_team_score: 105,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 6,
    },
};
