export const dayFour = {
    data: [
        {
            id: 858438,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 14,
                abbreviation: 'LAL',
                city: 'Los Angeles',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Los Angeles Lakers',
                name: 'Lakers',
            },
            home_team_score: 122,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 24,
                abbreviation: 'PHX',
                city: 'Phoenix',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Phoenix Suns',
                name: 'Suns',
            },
            visitor_team_score: 111,
        },
        {
            id: 858446,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 18,
                abbreviation: 'MIN',
                city: 'Minnesota',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Minnesota Timberwolves',
                name: 'Timberwolves',
            },
            home_team_score: 125,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 1,
                abbreviation: 'ATL',
                city: 'Atlanta',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Atlanta Hawks',
                name: 'Hawks',
            },
            visitor_team_score: 124,
        },
        {
            id: 858440,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 16,
                abbreviation: 'MIA',
                city: 'Miami',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Miami Heat',
                name: 'Heat',
            },
            home_team_score: 127,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            visitor_team_score: 120,
        },
        {
            id: 858439,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 30,
                abbreviation: 'WAS',
                city: 'Washington',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Washington Wizards',
                name: 'Wizards',
            },
            home_team_score: 104,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 8,
                abbreviation: 'DEN',
                city: 'Denver',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Denver Nuggets',
                name: 'Nuggets',
            },
            visitor_team_score: 118,
        },
        {
            id: 858443,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 15,
                abbreviation: 'MEM',
                city: 'Memphis',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Memphis Grizzlies',
                name: 'Grizzlies',
            },
            home_team_score: 130,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 11,
                abbreviation: 'HOU',
                city: 'Houston',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Houston Rockets',
                name: 'Rockets',
            },
            visitor_team_score: 125,
        },
        {
            id: 858444,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 7,
                abbreviation: 'DAL',
                city: 'Dallas',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Dallas Mavericks',
                name: 'Mavericks',
            },
            home_team_score: 125,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 10,
                abbreviation: 'GSW',
                city: 'Golden State',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Golden State Warriors',
                name: 'Warriors',
            },
            visitor_team_score: 127,
        },
        {
            id: 858445,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 5,
                abbreviation: 'CHI',
                city: 'Chicago',
                conference: 'East',
                division: 'Central',
                full_name: 'Chicago Bulls',
                name: 'Bulls',
            },
            home_team_score: 91,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 23,
                abbreviation: 'PHI',
                city: 'Philadelphia',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Philadelphia 76ers',
                name: '76ers',
            },
            visitor_team_score: 116,
        },
        {
            id: 858441,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 28,
                abbreviation: 'TOR',
                city: 'Toronto',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Toronto Raptors',
                name: 'Raptors',
            },
            home_team_score: 114,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 12,
                abbreviation: 'IND',
                city: 'Indiana',
                conference: 'East',
                division: 'Central',
                full_name: 'Indiana Pacers',
                name: 'Pacers',
            },
            visitor_team_score: 118,
        },
        {
            id: 858442,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 17,
                abbreviation: 'MIL',
                city: 'Milwaukee',
                conference: 'East',
                division: 'Central',
                full_name: 'Milwaukee Bucks',
                name: 'Bucks',
            },
            home_team_score: 130,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 27,
                abbreviation: 'SAS',
                city: 'San Antonio',
                conference: 'West',
                division: 'Southwest',
                full_name: 'San Antonio Spurs',
                name: 'Spurs',
            },
            visitor_team_score: 94,
        },
        {
            id: 858437,
            date: '2023-03-22T00:00:00.000Z',
            home_team: {
                id: 29,
                abbreviation: 'UTA',
                city: 'Utah',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Utah Jazz',
                name: 'Jazz',
            },
            home_team_score: 115,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 25,
                abbreviation: 'POR',
                city: 'Portland',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Portland Trail Blazers',
                name: 'Trail Blazers',
            },
            visitor_team_score: 127,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 10,
    },
};
