export const dayFive = {
    data: [
        {
            id: 858436,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            home_team_score: 100,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            visitor_team_score: 101,
        },
        {
            id: 858432,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            home_team_score: 122,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 30,
                abbreviation: 'WAS',
                city: 'Washington',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Washington Wizards',
                name: 'Wizards',
            },
            visitor_team_score: 112,
        },
        {
            id: 858435,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            home_team_score: 119,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 27,
                abbreviation: 'SAS',
                city: 'San Antonio',
                conference: 'West',
                division: 'Southwest',
                full_name: 'San Antonio Spurs',
                name: 'Spurs',
            },
            visitor_team_score: 84,
        },
        {
            id: 858434,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 26,
                abbreviation: 'SAC',
                city: 'Sacramento',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Sacramento Kings',
                name: 'Kings',
            },
            home_team_score: 109,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 2,
                abbreviation: 'BOS',
                city: 'Boston',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Boston Celtics',
                name: 'Celtics',
            },
            visitor_team_score: 132,
        },
        {
            id: 858433,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 1,
                abbreviation: 'ATL',
                city: 'Atlanta',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Atlanta Hawks',
                name: 'Hawks',
            },
            home_team_score: 129,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 9,
                abbreviation: 'DET',
                city: 'Detroit',
                conference: 'East',
                division: 'Central',
                full_name: 'Detroit Pistons',
                name: 'Pistons',
            },
            visitor_team_score: 107,
        },
        {
            id: 858431,
            date: '2023-03-21T00:00:00.000Z',
            home_team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            home_team_score: 109,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            visitor_team_score: 115,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 6,
    },
};
