export const dayOne = {
    data: [
        {
            id: 858410,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 30,
                abbreviation: 'WAS',
                city: 'Washington',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Washington Wizards',
                name: 'Wizards',
            },
            home_team_score: 118,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 26,
                abbreviation: 'SAC',
                city: 'Sacramento',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Sacramento Kings',
                name: 'Kings',
            },
            visitor_team_score: 132,
        },
        {
            id: 858416,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 29,
                abbreviation: 'UTA',
                city: 'Utah',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Utah Jazz',
                name: 'Jazz',
            },
            home_team_score: 118,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 2,
                abbreviation: 'BOS',
                city: 'Boston',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Boston Celtics',
                name: 'Celtics',
            },
            visitor_team_score: 117,
        },
        {
            id: 858413,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            home_team_score: 108,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            visitor_team_score: 113,
        },
        {
            id: 858411,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            home_team_score: 116,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 8,
                abbreviation: 'DEN',
                city: 'Denver',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Denver Nuggets',
                name: 'Nuggets',
            },
            visitor_team_score: 110,
        },
        {
            id: 858412,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 5,
                abbreviation: 'CHI',
                city: 'Chicago',
                conference: 'East',
                division: 'Central',
                full_name: 'Chicago Bulls',
                name: 'Bulls',
            },
            home_team_score: 113,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 16,
                abbreviation: 'MIA',
                city: 'Miami',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Miami Heat',
                name: 'Heat',
            },
            visitor_team_score: 99,
        },
        {
            id: 858409,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 12,
                abbreviation: 'IND',
                city: 'Indiana',
                conference: 'East',
                division: 'Central',
                full_name: 'Indiana Pacers',
                name: 'Pacers',
            },
            home_team_score: 121,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 23,
                abbreviation: 'PHI',
                city: 'Philadelphia',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Philadelphia 76ers',
                name: '76ers',
            },
            visitor_team_score: 141,
        },
        {
            id: 858415,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 28,
                abbreviation: 'TOR',
                city: 'Toronto',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Toronto Raptors',
                name: 'Raptors',
            },
            home_team_score: 122,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 18,
                abbreviation: 'MIN',
                city: 'Minnesota',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Minnesota Timberwolves',
                name: 'Timberwolves',
            },
            visitor_team_score: 107,
        },
        {
            id: 858414,
            date: '2023-03-18T00:00:00.000Z',
            home_team: {
                id: 15,
                abbreviation: 'MEM',
                city: 'Memphis',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Memphis Grizzlies',
                name: 'Grizzlies',
            },
            home_team_score: 133,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 10,
                abbreviation: 'GSW',
                city: 'Golden State',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Golden State Warriors',
                name: 'Warriors',
            },
            visitor_team_score: 119,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 8,
    },
};
