export const daySeven = {
    data: [
        {
            id: 858451,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 14,
                abbreviation: 'LAL',
                city: 'Los Angeles',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Los Angeles Lakers',
                name: 'Lakers',
            },
            home_team_score: 116,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            visitor_team_score: 111,
        },
        {
            id: 858452,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 25,
                abbreviation: 'POR',
                city: 'Portland',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Portland Trail Blazers',
                name: 'Trail Blazers',
            },
            home_team_score: 96,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 5,
                abbreviation: 'CHI',
                city: 'Chicago',
                conference: 'East',
                division: 'Central',
                full_name: 'Chicago Bulls',
                name: 'Bulls',
            },
            visitor_team_score: 124,
        },
        {
            id: 858460,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 26,
                abbreviation: 'SAC',
                city: 'Sacramento',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Sacramento Kings',
                name: 'Kings',
            },
            home_team_score: 135,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 24,
                abbreviation: 'PHX',
                city: 'Phoenix',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Phoenix Suns',
                name: 'Suns',
            },
            visitor_team_score: 127,
        },
        {
            id: 858459,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 30,
                abbreviation: 'WAS',
                city: 'Washington',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Washington Wizards',
                name: 'Wizards',
            },
            home_team_score: 136,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 27,
                abbreviation: 'SAS',
                city: 'San Antonio',
                conference: 'West',
                division: 'Southwest',
                full_name: 'San Antonio Spurs',
                name: 'Spurs',
            },
            visitor_team_score: 124,
        },
        {
            id: 858457,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 2,
                abbreviation: 'BOS',
                city: 'Boston',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Boston Celtics',
                name: 'Celtics',
            },
            home_team_score: 120,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 12,
                abbreviation: 'IND',
                city: 'Indiana',
                conference: 'East',
                division: 'Central',
                full_name: 'Indiana Pacers',
                name: 'Pacers',
            },
            visitor_team_score: 95,
        },
        {
            id: 858455,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 7,
                abbreviation: 'DAL',
                city: 'Dallas',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Dallas Mavericks',
                name: 'Mavericks',
            },
            home_team_score: 109,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            visitor_team_score: 117,
        },
        {
            id: 858453,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 28,
                abbreviation: 'TOR',
                city: 'Toronto',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Toronto Raptors',
                name: 'Raptors',
            },
            home_team_score: 118,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 9,
                abbreviation: 'DET',
                city: 'Detroit',
                conference: 'East',
                division: 'Central',
                full_name: 'Detroit Pistons',
                name: 'Pistons',
            },
            visitor_team_score: 97,
        },
        {
            id: 858458,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 29,
                abbreviation: 'UTA',
                city: 'Utah',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Utah Jazz',
                name: 'Jazz',
            },
            home_team_score: 116,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 17,
                abbreviation: 'MIL',
                city: 'Milwaukee',
                conference: 'East',
                division: 'Central',
                full_name: 'Milwaukee Bucks',
                name: 'Bucks',
            },
            visitor_team_score: 144,
        },
        {
            id: 858456,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 15,
                abbreviation: 'MEM',
                city: 'Memphis',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Memphis Grizzlies',
                name: 'Grizzlies',
            },
            home_team_score: 151,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 11,
                abbreviation: 'HOU',
                city: 'Houston',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Houston Rockets',
                name: 'Rockets',
            },
            visitor_team_score: 114,
        },
        {
            id: 858454,
            date: '2023-03-24T00:00:00.000Z',
            home_team: {
                id: 10,
                abbreviation: 'GSW',
                city: 'Golden State',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Golden State Warriors',
                name: 'Warriors',
            },
            home_team_score: 120,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 23,
                abbreviation: 'PHI',
                city: 'Philadelphia',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Philadelphia 76ers',
                name: '76ers',
            },
            visitor_team_score: 112,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 10,
    },
};
