export const dayTwo = {
    data: [
        {
            id: 858421,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 25,
                abbreviation: 'POR',
                city: 'Portland',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Portland Trail Blazers',
                name: 'Trail Blazers',
            },
            home_team_score: 102,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            visitor_team_score: 117,
        },
        {
            id: 858422,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            home_team_score: 124,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 24,
                abbreviation: 'PHX',
                city: 'Phoenix',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Phoenix Suns',
                name: 'Suns',
            },
            visitor_team_score: 120,
        },
        {
            id: 858424,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            home_team_score: 102,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 8,
                abbreviation: 'DEN',
                city: 'Denver',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Denver Nuggets',
                name: 'Nuggets',
            },
            visitor_team_score: 108,
        },
        {
            id: 858420,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 14,
                abbreviation: 'LAL',
                city: 'Los Angeles',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Los Angeles Lakers',
                name: 'Lakers',
            },
            home_team_score: 111,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            visitor_team_score: 105,
        },
        {
            id: 858418,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 11,
                abbreviation: 'HOU',
                city: 'Houston',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Houston Rockets',
                name: 'Rockets',
            },
            home_team_score: 107,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            visitor_team_score: 117,
        },
        {
            id: 858423,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 17,
                abbreviation: 'MIL',
                city: 'Milwaukee',
                conference: 'East',
                division: 'Central',
                full_name: 'Milwaukee Bucks',
                name: 'Bucks',
            },
            home_team_score: 118,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 28,
                abbreviation: 'TOR',
                city: 'Toronto',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Toronto Raptors',
                name: 'Raptors',
            },
            visitor_team_score: 111,
        },
        {
            id: 858419,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 9,
                abbreviation: 'DET',
                city: 'Detroit',
                conference: 'East',
                division: 'Central',
                full_name: 'Detroit Pistons',
                name: 'Pistons',
            },
            home_team_score: 100,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 16,
                abbreviation: 'MIA',
                city: 'Miami',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Miami Heat',
                name: 'Heat',
            },
            visitor_team_score: 112,
        },
        {
            id: 858417,
            date: '2023-03-19T00:00:00.000Z',
            home_team: {
                id: 27,
                abbreviation: 'SAS',
                city: 'San Antonio',
                conference: 'West',
                division: 'Southwest',
                full_name: 'San Antonio Spurs',
                name: 'Spurs',
            },
            home_team_score: 126,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 1,
                abbreviation: 'ATL',
                city: 'Atlanta',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Atlanta Hawks',
                name: 'Hawks',
            },
            visitor_team_score: 118,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 8,
    },
};
