export const dayThree = {
    data: [
        {
            id: 858426,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 23,
                abbreviation: 'PHI',
                city: 'Philadelphia',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Philadelphia 76ers',
                name: '76ers',
            },
            home_team_score: 105,
            period: 6,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 5,
                abbreviation: 'CHI',
                city: 'Chicago',
                conference: 'East',
                division: 'Central',
                full_name: 'Chicago Bulls',
                name: 'Bulls',
            },
            visitor_team_score: 109,
        },
        {
            id: 858427,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 15,
                abbreviation: 'MEM',
                city: 'Memphis',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Memphis Grizzlies',
                name: 'Grizzlies',
            },
            home_team_score: 112,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 7,
                abbreviation: 'DAL',
                city: 'Dallas',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Dallas Mavericks',
                name: 'Mavericks',
            },
            visitor_team_score: 108,
        },
        {
            id: 858430,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 11,
                abbreviation: 'HOU',
                city: 'Houston',
                conference: 'West',
                division: 'Southwest',
                full_name: 'Houston Rockets',
                name: 'Rockets',
            },
            home_team_score: 108,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 10,
                abbreviation: 'GSW',
                city: 'Golden State',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Golden State Warriors',
                name: 'Warriors',
            },
            visitor_team_score: 121,
        },
        {
            id: 858429,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 29,
                abbreviation: 'UTA',
                city: 'Utah',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Utah Jazz',
                name: 'Jazz',
            },
            home_team_score: 128,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 26,
                abbreviation: 'SAC',
                city: 'Sacramento',
                conference: 'West',
                division: 'Pacific',
                full_name: 'Sacramento Kings',
                name: 'Kings',
            },
            visitor_team_score: 120,
        },
        {
            id: 858428,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            home_team_score: 134,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 18,
                abbreviation: 'MIN',
                city: 'Minnesota',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Minnesota Timberwolves',
                name: 'Timberwolves',
            },
            visitor_team_score: 140,
        },
        {
            id: 858425,
            date: '2023-03-20T00:00:00.000Z',
            home_team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            home_team_score: 115,
            period: 4,
            postseason: false,
            season: 2022,
            status: 'Final',
            time: 'Final',
            visitor_team: {
                id: 12,
                abbreviation: 'IND',
                city: 'Indiana',
                conference: 'East',
                division: 'Central',
                full_name: 'Indiana Pacers',
                name: 'Pacers',
            },
            visitor_team_score: 109,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 25,
        total_count: 6,
    },
};
