export const game2 = {
    data: [
        {
            id: 13810463,
            ast: 6,
            blk: 1,
            dreb: 3,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.5833333,
            fga: 12,
            fgm: 7,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '32',
            oreb: 0,
            pf: 2,
            player: {
                id: 17896026,
                first_name: 'Franz',
                height_feet: null,
                height_inches: null,
                last_name: 'Wagner',
                position: 'F',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 16,
            reb: 3,
            stl: 2,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 2,
        },
        {
            id: 13810464,
            ast: 4,
            blk: 2,
            dreb: 6,
            fg3_pct: 0.5,
            fg3a: 4,
            fg3m: 2,
            fg_pct: 0.4117647,
            fga: 17,
            fgm: 7,
            ft_pct: 0.8333333,
            fta: 6,
            ftm: 5,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '34',
            oreb: 0,
            pf: 3,
            player: {
                id: 38017683,
                first_name: 'Paolo',
                height_feet: null,
                height_inches: null,
                last_name: 'Banchero',
                position: 'F',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 21,
            reb: 6,
            stl: 2,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 3,
        },
        {
            id: 13810465,
            ast: 0,
            blk: 0,
            dreb: 7,
            fg3_pct: 0.4,
            fg3a: 5,
            fg3m: 2,
            fg_pct: 0.53846157,
            fga: 13,
            fgm: 7,
            ft_pct: 0,
            fta: 1,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '31',
            oreb: 1,
            pf: 3,
            player: {
                id: 85,
                first_name: 'Wendell',
                height_feet: 6,
                height_inches: 10,
                last_name: 'Carter Jr.',
                position: 'F',
                team_id: 22,
                weight_pounds: 255,
            },
            pts: 16,
            reb: 8,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810466,
            ast: 1,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.42857143,
            fg3a: 7,
            fg3m: 3,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '27',
            oreb: 1,
            pf: 4,
            player: {
                id: 196,
                first_name: 'Gary',
                height_feet: 6,
                height_inches: 4,
                last_name: 'Harris',
                position: 'G',
                team_id: 22,
                weight_pounds: 210,
            },
            pts: 9,
            reb: 2,
            stl: 2,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810467,
            ast: 8,
            blk: 1,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.36363637,
            fga: 11,
            fgm: 4,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '34',
            oreb: 0,
            pf: 2,
            player: {
                id: 165,
                first_name: 'Markelle',
                height_feet: 6,
                height_inches: 4,
                last_name: 'Fultz',
                position: 'G',
                team_id: 22,
                weight_pounds: 200,
            },
            pts: 10,
            reb: 1,
            stl: 1,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 3,
        },
        {
            id: 13810468,
            ast: 1,
            blk: 1,
            dreb: 5,
            fg3_pct: 0.6666667,
            fg3a: 6,
            fg3m: 4,
            fg_pct: 0.46153846,
            fga: 13,
            fgm: 6,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '26',
            oreb: 1,
            pf: 2,
            player: {
                id: 3547251,
                first_name: 'Cole',
                height_feet: null,
                height_inches: null,
                last_name: 'Anthony',
                position: 'G',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 18,
            reb: 6,
            stl: 1,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 1,
        },
        {
            id: 13810469,
            ast: 1,
            blk: 0,
            dreb: 4,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 1,
            fga: 1,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '14',
            oreb: 1,
            pf: 2,
            player: {
                id: 666442,
                first_name: 'Goga',
                height_feet: null,
                height_inches: null,
                last_name: 'Bitadze',
                position: 'C',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 2,
            reb: 5,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810470,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666451,
                first_name: 'Bol',
                height_feet: null,
                height_inches: null,
                last_name: 'Bol',
                position: 'C',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810471,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 86,
                first_name: 'Michael',
                height_feet: null,
                height_inches: null,
                last_name: 'Carter-Williams',
                position: 'G',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810472,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017607,
                first_name: 'Kevon',
                height_feet: null,
                height_inches: null,
                last_name: 'Harris',
                position: 'G',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810473,
            ast: 1,
            blk: 2,
            dreb: 3,
            fg3_pct: 0.4,
            fg3a: 5,
            fg3m: 2,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '25',
            oreb: 3,
            pf: 1,
            player: {
                id: 38017724,
                first_name: 'Caleb',
                height_feet: null,
                height_inches: null,
                last_name: 'Houstan',
                position: 'G',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 8,
            reb: 6,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 2,
        },
        {
            id: 13810474,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666818,
                first_name: 'Chuma',
                height_feet: null,
                height_inches: null,
                last_name: 'Okeke',
                position: 'F',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810475,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666885,
                first_name: 'Admiral',
                height_feet: null,
                height_inches: null,
                last_name: 'Schofield',
                position: 'F',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810476,
            ast: 3,
            blk: 0,
            dreb: 5,
            fg3_pct: 0,
            fg3a: 3,
            fg3m: 0,
            fg_pct: 0.2857143,
            fga: 7,
            fgm: 2,
            ft_pct: 0.875,
            fta: 8,
            ftm: 7,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '17',
            oreb: 2,
            pf: 0,
            player: {
                id: 462,
                first_name: 'Moritz',
                height_feet: 6,
                height_inches: 11,
                last_name: 'Wagner',
                position: 'C',
                team_id: 22,
                weight_pounds: 245,
            },
            pts: 11,
            reb: 7,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 3,
        },
        {
            id: 13810477,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 229,
                first_name: 'Jonathan',
                height_feet: 6,
                height_inches: 10,
                last_name: 'Isaac',
                position: 'F',
                team_id: 22,
                weight_pounds: 210,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810478,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896073,
                first_name: 'Jalen',
                height_feet: null,
                height_inches: null,
                last_name: 'Suggs',
                position: 'G',
                team_id: 22,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 22,
                abbreviation: 'ORL',
                city: 'Orlando',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Orlando Magic',
                name: 'Magic',
            },
            turnover: 0,
        },
        {
            id: 13810479,
            ast: 3,
            blk: 0,
            dreb: 2,
            fg3_pct: 0,
            fg3a: 3,
            fg3m: 0,
            fg_pct: 0.25,
            fga: 12,
            fgm: 3,
            ft_pct: 0.6666667,
            fta: 6,
            ftm: 4,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '30',
            oreb: 0,
            pf: 1,
            player: {
                id: 666423,
                first_name: 'RJ',
                height_feet: null,
                height_inches: null,
                last_name: 'Barrett',
                position: 'F-G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 10,
            reb: 2,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 5,
        },
        {
            id: 13810480,
            ast: 4,
            blk: 2,
            dreb: 9,
            fg3_pct: 0.22222222,
            fg3a: 9,
            fg3m: 2,
            fg_pct: 0.35,
            fga: 20,
            fgm: 7,
            ft_pct: 0.7,
            fta: 10,
            ftm: 7,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '36',
            oreb: 0,
            pf: 4,
            player: {
                id: 387,
                first_name: 'Julius',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Randle',
                position: 'F',
                team_id: 20,
                weight_pounds: 250,
            },
            pts: 23,
            reb: 9,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 1,
        },
        {
            id: 13810481,
            ast: 0,
            blk: 4,
            dreb: 6,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 1,
            fga: 1,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '31',
            oreb: 6,
            pf: 0,
            player: {
                id: 399,
                first_name: 'Mitchell',
                height_feet: 7,
                height_inches: 1,
                last_name: 'Robinson',
                position: 'C',
                team_id: 20,
                weight_pounds: 240,
            },
            pts: 2,
            reb: 12,
            stl: 1,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 2,
        },
        {
            id: 13810482,
            ast: 7,
            blk: 1,
            dreb: 3,
            fg3_pct: 0.2857143,
            fg3a: 7,
            fg3m: 2,
            fg_pct: 0.4117647,
            fga: 17,
            fgm: 7,
            ft_pct: 0.9,
            fta: 10,
            ftm: 9,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '42',
            oreb: 2,
            pf: 0,
            player: {
                id: 3547269,
                first_name: 'Immanuel',
                height_feet: null,
                height_inches: null,
                last_name: 'Quickley',
                position: 'G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 25,
            reb: 5,
            stl: 2,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 3,
        },
        {
            id: 13810483,
            ast: 6,
            blk: 0,
            dreb: 3,
            fg3_pct: 0.5,
            fg3a: 10,
            fg3m: 5,
            fg_pct: 0.5555556,
            fga: 18,
            fgm: 10,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '38',
            oreb: 2,
            pf: 3,
            player: {
                id: 17895858,
                first_name: 'Quentin',
                height_feet: null,
                height_inches: null,
                last_name: 'Grimes',
                position: 'G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 25,
            reb: 5,
            stl: 3,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810484,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 73,
                first_name: 'Jalen',
                height_feet: 6,
                height_inches: 3,
                last_name: 'Brunson',
                position: 'G',
                team_id: 20,
                weight_pounds: 190,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810485,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 160,
                first_name: 'Evan',
                height_feet: 6,
                height_inches: 7,
                last_name: 'Fournier',
                position: 'G-F',
                team_id: 20,
                weight_pounds: 205,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810486,
            ast: 2,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.33333334,
            fg3a: 3,
            fg3m: 1,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '29',
            oreb: 1,
            pf: 4,
            player: {
                id: 202,
                first_name: 'Josh',
                height_feet: 6,
                height_inches: 5,
                last_name: 'Hart',
                position: 'G',
                team_id: 20,
                weight_pounds: 215,
            },
            pts: 7,
            reb: 5,
            stl: 1,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 1,
        },
        {
            id: 13810487,
            ast: 3,
            blk: 2,
            dreb: 2,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 1,
            fga: 3,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '16',
            oreb: 2,
            pf: 2,
            player: {
                id: 201,
                first_name: 'Isaiah',
                height_feet: 7,
                height_inches: 0,
                last_name: 'Hartenstein',
                position: 'F-C',
                team_id: 20,
                weight_pounds: 249,
            },
            pts: 6,
            reb: 4,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810488,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666675,
                first_name: 'DaQuan',
                height_feet: null,
                height_inches: null,
                last_name: 'Jeffries',
                position: 'F',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810489,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0.33333334,
            fg3a: 3,
            fg3m: 1,
            fg_pct: 0.33333334,
            fga: 3,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '06',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896033,
                first_name: 'Miles',
                height_feet: null,
                height_inches: null,
                last_name: 'McBride',
                position: 'G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 3,
            reb: 0,
            stl: 1,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 1,
        },
        {
            id: 13810490,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 401,
                first_name: 'Derrick',
                height_feet: 6,
                height_inches: 3,
                last_name: 'Rose',
                position: 'G',
                team_id: 20,
                weight_pounds: 200,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810493,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017720,
                first_name: 'Trevor',
                height_feet: null,
                height_inches: null,
                last_name: 'Keels',
                position: 'G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810494,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896089,
                first_name: 'Duane',
                height_feet: null,
                height_inches: null,
                last_name: 'Washington Jr.',
                position: 'G',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810491,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896063,
                first_name: 'Jericho',
                height_feet: null,
                height_inches: null,
                last_name: 'Sims',
                position: 'F',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
        {
            id: 13810492,
            ast: 0,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.2,
            fg3a: 5,
            fg3m: 1,
            fg_pct: 0.2857143,
            fga: 7,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858447,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 22,
                home_team_score: 111,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 20,
                visitor_team_score: 106,
            },
            min: '12',
            oreb: 0,
            pf: 1,
            player: {
                id: 3547243,
                first_name: 'Obi',
                height_feet: null,
                height_inches: null,
                last_name: 'Toppin',
                position: 'F',
                team_id: 20,
                weight_pounds: null,
            },
            pts: 5,
            reb: 2,
            stl: 0,
            team: {
                id: 20,
                abbreviation: 'NYK',
                city: 'New York',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'New York Knicks',
                name: 'Knicks',
            },
            turnover: 0,
        },
    ],
};
