import {
    boxscoreDataType,
    gameStatsDataType,
} from '../../types/basketballdata';

interface customGameType extends Omit<gameStatsDataType, 'date'> {
    date: string;
}

interface customBoxscoreType extends Omit<boxscoreDataType, 'game'> {
    game: customGameType;
}

//Game ID 858450
export const game1: customBoxscoreType = {
    data: [
        {
            id: 13810495,
            ast: 1,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.25,
            fg3a: 4,
            fg3m: 1,
            fg_pct: 0.16666667,
            fga: 6,
            fgm: 1,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '22',
            oreb: 1,
            pf: 2,
            player: {
                id: 666679,
                first_name: 'Cameron',
                height_feet: null,
                height_inches: null,
                last_name: 'Johnson',
                position: 'F',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 5,
            reb: 3,
            stl: 2,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 2,
        },
        {
            id: 13810496,
            ast: 1,
            blk: 2,
            dreb: 2,
            fg3_pct: 0,
            fg3a: 4,
            fg3m: 0,
            fg_pct: 0,
            fga: 6,
            fgm: 0,
            ft_pct: 1,
            fta: 4,
            ftm: 4,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '22',
            oreb: 3,
            pf: 0,
            player: {
                id: 158,
                first_name: 'Dorian',
                height_feet: 6,
                height_inches: 8,
                last_name: 'Finney-Smith',
                position: 'F',
                team_id: 3,
                weight_pounds: 220,
            },
            pts: 4,
            reb: 5,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 3,
        },
        {
            id: 13810497,
            ast: 2,
            blk: 3,
            dreb: 6,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.4,
            fga: 10,
            fgm: 4,
            ft_pct: 0.75,
            fta: 4,
            ftm: 3,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '34',
            oreb: 3,
            pf: 4,
            player: {
                id: 666508,
                first_name: 'Nicolas',
                height_feet: null,
                height_inches: null,
                last_name: 'Claxton',
                position: 'F-C',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 11,
            reb: 9,
            stl: 1,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 1,
        },
        {
            id: 13810498,
            ast: 1,
            blk: 0,
            dreb: 5,
            fg3_pct: 0.2857143,
            fg3a: 7,
            fg3m: 2,
            fg_pct: 0.57894737,
            fga: 19,
            fgm: 11,
            ft_pct: 1,
            fta: 8,
            ftm: 8,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '34',
            oreb: 1,
            pf: 3,
            player: {
                id: 61,
                first_name: 'Mikal',
                height_feet: 6,
                height_inches: 7,
                last_name: 'Bridges',
                position: 'F',
                team_id: 3,
                weight_pounds: 210,
            },
            pts: 32,
            reb: 6,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 1,
        },
        {
            id: 13810499,
            ast: 12,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.5,
            fg3a: 4,
            fg3m: 2,
            fg_pct: 0.6,
            fga: 15,
            fgm: 9,
            ft_pct: 0.8333333,
            fta: 6,
            ftm: 5,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '42',
            oreb: 0,
            pf: 1,
            player: {
                id: 130,
                first_name: 'Spencer',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Dinwiddie',
                position: 'G',
                team_id: 3,
                weight_pounds: 210,
            },
            pts: 25,
            reb: 4,
            stl: 1,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 2,
        },
        {
            id: 13810500,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666476,
                first_name: 'Moses',
                height_feet: null,
                height_inches: null,
                last_name: 'Brown',
                position: 'C',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810501,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '06',
            oreb: 0,
            pf: 2,
            player: {
                id: 114,
                first_name: 'Seth',
                height_feet: 6,
                height_inches: 2,
                last_name: 'Curry',
                position: 'G',
                team_id: 3,
                weight_pounds: 185,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 1,
        },
        {
            id: 13810502,
            ast: 0,
            blk: 0,
            dreb: 3,
            fg3_pct: 0.625,
            fg3a: 8,
            fg3m: 5,
            fg_pct: 0.625,
            fga: 8,
            fgm: 5,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '23',
            oreb: 0,
            pf: 1,
            player: {
                id: 197,
                first_name: 'Joe',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Harris',
                position: 'F-G',
                team_id: 3,
                weight_pounds: 218,
            },
            pts: 15,
            reb: 3,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810503,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 319,
                first_name: 'Patty',
                height_feet: 6,
                height_inches: 0,
                last_name: 'Mills',
                position: 'G',
                team_id: 3,
                weight_pounds: 180,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810504,
            ast: 2,
            blk: 0,
            dreb: 8,
            fg3_pct: 0.5,
            fg3a: 4,
            fg3m: 2,
            fg_pct: 0.5,
            fga: 8,
            fgm: 4,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '30',
            oreb: 0,
            pf: 5,
            player: {
                id: 351,
                first_name: 'Royce',
                height_feet: 6,
                height_inches: 6,
                last_name: "O'Neale",
                position: 'F',
                team_id: 3,
                weight_pounds: 226,
            },
            pts: 12,
            reb: 8,
            stl: 1,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 3,
        },
        {
            id: 13810505,
            ast: 2,
            blk: 2,
            dreb: 2,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.6,
            fga: 5,
            fgm: 3,
            ft_pct: 0,
            fta: 1,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '14',
            oreb: 1,
            pf: 2,
            player: {
                id: 17896038,
                first_name: "Day'Ron",
                height_feet: null,
                height_inches: null,
                last_name: 'Sharpe',
                position: 'C',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 6,
            reb: 3,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 2,
        },
        {
            id: 13810506,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 432,
                first_name: 'Edmond',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Sumner',
                position: 'G',
                team_id: 3,
                weight_pounds: 176,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810507,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896048,
                first_name: 'Cam',
                height_feet: null,
                height_inches: null,
                last_name: 'Thomas',
                position: 'G',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810508,
            ast: 2,
            blk: 0,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.6666667,
            fga: 3,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '13',
            oreb: 0,
            pf: 1,
            player: {
                id: 470,
                first_name: 'Yuta',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Watanabe',
                position: 'G',
                team_id: 3,
                weight_pounds: 205,
            },
            pts: 4,
            reb: 1,
            stl: 2,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810509,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896049,
                first_name: 'David',
                height_feet: null,
                height_inches: null,
                last_name: 'Duke Jr.',
                position: 'G',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810510,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 417,
                first_name: 'Ben',
                height_feet: 6,
                height_inches: 10,
                last_name: 'Simmons',
                position: 'G-F',
                team_id: 3,
                weight_pounds: 230,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810511,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 19465585,
                first_name: 'Dru',
                height_feet: null,
                height_inches: null,
                last_name: 'Smith',
                position: 'G',
                team_id: 3,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 3,
                abbreviation: 'BKN',
                city: 'Brooklyn',
                conference: 'East',
                division: 'Atlantic',
                full_name: 'Brooklyn Nets',
                name: 'Nets',
            },
            turnover: 0,
        },
        {
            id: 13810514,
            ast: 1,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.75,
            fg3a: 4,
            fg3m: 3,
            fg_pct: 0.8,
            fga: 5,
            fgm: 4,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '30',
            oreb: 0,
            pf: 3,
            player: {
                id: 3547247,
                first_name: 'Isaac',
                height_feet: null,
                height_inches: null,
                last_name: 'Okoro',
                position: 'F-G',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 11,
            reb: 1,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810517,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547163,
                first_name: 'Mamadi',
                height_feet: null,
                height_inches: null,
                last_name: 'Diakite',
                position: 'F',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810518,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 184,
                first_name: 'Danny',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Green',
                position: 'G-F',
                team_id: 6,
                weight_pounds: 215,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810519,
            ast: 2,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.4,
            fg3a: 5,
            fg3m: 2,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 1,
            fta: 4,
            ftm: 4,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '22',
            oreb: 1,
            pf: 4,
            player: {
                id: 277,
                first_name: 'Caris',
                height_feet: 6,
                height_inches: 7,
                last_name: 'LeVert',
                position: 'G',
                team_id: 6,
                weight_pounds: 204,
            },
            pts: 12,
            reb: 3,
            stl: 2,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 3,
        },
        {
            id: 13810520,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 284,
                first_name: 'Robin',
                height_feet: 7,
                height_inches: 0,
                last_name: 'Lopez',
                position: 'C',
                team_id: 6,
                weight_pounds: 275,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810521,
            ast: 0,
            blk: 1,
            dreb: 2,
            fg3_pct: 0.2,
            fg3a: 5,
            fg3m: 1,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 0.5,
            fta: 2,
            ftm: 1,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '22',
            oreb: 0,
            pf: 3,
            player: {
                id: 359,
                first_name: 'Cedi',
                height_feet: 6,
                height_inches: 8,
                last_name: 'Osman',
                position: 'F',
                team_id: 6,
                weight_pounds: 215,
            },
            pts: 8,
            reb: 2,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810522,
            ast: 7,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0,
            fga: 1,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '20',
            oreb: 0,
            pf: 2,
            player: {
                id: 404,
                first_name: 'Ricky',
                height_feet: 6,
                height_inches: 4,
                last_name: 'Rubio',
                position: 'G',
                team_id: 6,
                weight_pounds: 190,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810523,
            ast: 0,
            blk: 0,
            dreb: 1,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 0.5,
            fga: 2,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '04',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547279,
                first_name: 'Lamar',
                height_feet: null,
                height_inches: null,
                last_name: 'Stevens',
                position: 'F',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 3,
            reb: 1,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810524,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666940,
                first_name: 'Dean',
                height_feet: null,
                height_inches: null,
                last_name: 'Wade',
                position: 'F',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810525,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547299,
                first_name: 'Sam',
                height_feet: null,
                height_inches: null,
                last_name: 'Merrill',
                position: 'G',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810526,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017662,
                first_name: 'Isaiah',
                height_feet: null,
                height_inches: null,
                last_name: 'Mobley',
                position: 'F',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810527,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 343,
                first_name: 'Raul',
                height_feet: 6,
                height_inches: 1,
                last_name: 'Neto',
                position: 'G',
                team_id: 6,
                weight_pounds: 179,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810528,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666971,
                first_name: 'Dylan',
                height_feet: null,
                height_inches: null,
                last_name: 'Windler',
                position: 'G-F',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810512,
            ast: 3,
            blk: 4,
            dreb: 11,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.6111111,
            fga: 18,
            fgm: 11,
            ft_pct: 0.6666667,
            fta: 6,
            ftm: 4,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '40',
            oreb: 5,
            pf: 1,
            player: {
                id: 17896076,
                first_name: 'Evan',
                height_feet: null,
                height_inches: null,
                last_name: 'Mobley',
                position: 'F-C',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 26,
            reb: 16,
            stl: 1,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 0,
        },
        {
            id: 13810513,
            ast: 2,
            blk: 1,
            dreb: 5,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.5555556,
            fga: 9,
            fgm: 5,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '30',
            oreb: 5,
            pf: 3,
            player: {
                id: 9,
                first_name: 'Jarrett',
                height_feet: 6,
                height_inches: 11,
                last_name: 'Allen',
                position: 'C',
                team_id: 6,
                weight_pounds: 237,
            },
            pts: 12,
            reb: 10,
            stl: 1,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 2,
        },
        {
            id: 13810515,
            ast: 1,
            blk: 1,
            dreb: 4,
            fg3_pct: 0.33333334,
            fg3a: 9,
            fg3m: 3,
            fg_pct: 0.45833334,
            fga: 24,
            fgm: 11,
            ft_pct: 0.6666667,
            fta: 9,
            ftm: 6,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '33',
            oreb: 2,
            pf: 3,
            player: {
                id: 322,
                first_name: 'Donovan',
                height_feet: 6,
                height_inches: 3,
                last_name: 'Mitchell',
                position: 'G',
                team_id: 6,
                weight_pounds: 215,
            },
            pts: 31,
            reb: 6,
            stl: 0,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 1,
        },
        {
            id: 13810516,
            ast: 8,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.33333334,
            fg3a: 6,
            fg3m: 2,
            fg_pct: 0.25,
            fga: 16,
            fgm: 4,
            ft_pct: 1,
            fta: 3,
            ftm: 3,
            game: {
                id: 858450,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 3,
                home_team_score: 114,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 6,
                visitor_team_score: 116,
            },
            min: '39',
            oreb: 0,
            pf: 2,
            player: {
                id: 666581,
                first_name: 'Darius',
                height_feet: null,
                height_inches: null,
                last_name: 'Garland',
                position: 'G',
                team_id: 6,
                weight_pounds: null,
            },
            pts: 13,
            reb: 1,
            stl: 3,
            team: {
                id: 6,
                abbreviation: 'CLE',
                city: 'Cleveland',
                conference: 'East',
                division: 'Central',
                full_name: 'Cleveland Cavaliers',
                name: 'Cavaliers',
            },
            turnover: 3,
        },
    ],
    meta: {
        total_pages: 1,
        current_page: 1,
        next_page: null,
        per_page: 100,
        total_count: 34,
    },
};
