import { boxscoreDataType } from '../../types/basketballdata';

// Game ID 858449
export const game3: boxscoreDataType = {
    data: [
        {
            id: 13812067,
            ast: 3,
            blk: 0,
            dreb: 3,
            fg3_pct: 0,
            fg3a: 4,
            fg3m: 0,
            fg_pct: 0.3,
            fga: 10,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '25',
            oreb: 1,
            pf: 1,
            player: {
                id: 328,
                first_name: 'Marcus',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Morris',
                position: 'F',
                team_id: 13,
                weight_pounds: 235,
            },
            pts: 6,
            reb: 4,
            stl: 1,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 1,
        },
        {
            id: 13812068,
            ast: 6,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.75,
            fg3a: 4,
            fg3m: 3,
            fg_pct: 0.8666667,
            fga: 15,
            fgm: 13,
            ft_pct: 0.75,
            fta: 4,
            ftm: 3,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '34',
            oreb: 2,
            pf: 2,
            player: {
                id: 274,
                first_name: 'Kawhi',
                height_feet: 6,
                height_inches: 7,
                last_name: 'Leonard',
                position: 'F',
                team_id: 13,
                weight_pounds: 230,
            },
            pts: 32,
            reb: 6,
            stl: 4,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 2,
        },
        {
            id: 13812069,
            ast: 1,
            blk: 2,
            dreb: 9,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.6666667,
            fga: 3,
            fgm: 2,
            ft_pct: 1,
            fta: 2,
            ftm: 2,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '24',
            oreb: 1,
            pf: 1,
            player: {
                id: 493,
                first_name: 'Ivica',
                height_feet: 7,
                height_inches: 1,
                last_name: 'Zubac',
                position: 'C',
                team_id: 13,
                weight_pounds: 240,
            },
            pts: 6,
            reb: 10,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 1,
        },
        {
            id: 13812070,
            ast: 2,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.4,
            fg3a: 5,
            fg3m: 2,
            fg_pct: 0.33333334,
            fga: 9,
            fgm: 3,
            ft_pct: 0,
            fta: 1,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '22',
            oreb: 1,
            pf: 2,
            player: {
                id: 178,
                first_name: 'Eric',
                height_feet: 6,
                height_inches: 4,
                last_name: 'Gordon',
                position: 'G',
                team_id: 13,
                weight_pounds: 215,
            },
            pts: 8,
            reb: 3,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 2,
        },
        {
            id: 13812071,
            ast: 7,
            blk: 1,
            dreb: 1,
            fg3_pct: 0.5,
            fg3a: 4,
            fg3m: 2,
            fg_pct: 0.61538464,
            fga: 13,
            fgm: 8,
            ft_pct: 0.75,
            fta: 8,
            ftm: 6,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '30',
            oreb: 1,
            pf: 2,
            player: {
                id: 472,
                first_name: 'Russell',
                height_feet: 6,
                height_inches: 3,
                last_name: 'Westbrook',
                position: 'G',
                team_id: 13,
                weight_pounds: 200,
            },
            pts: 24,
            reb: 2,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 4,
        },
        {
            id: 13812075,
            ast: 7,
            blk: 1,
            dreb: 3,
            fg3_pct: 0.5714286,
            fg3a: 7,
            fg3m: 4,
            fg_pct: 0.46153846,
            fga: 13,
            fgm: 6,
            ft_pct: 0,
            fta: 1,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '26',
            oreb: 1,
            pf: 0,
            player: {
                id: 17896031,
                first_name: "Nah'Shon",
                height_feet: null,
                height_inches: null,
                last_name: 'Hyland',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 16,
            reb: 4,
            stl: 1,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 1,
        },
        {
            id: 13812076,
            ast: 3,
            blk: 0,
            dreb: 3,
            fg3_pct: 0.33333334,
            fg3a: 6,
            fg3m: 2,
            fg_pct: 0.4,
            fga: 10,
            fgm: 4,
            ft_pct: 1,
            fta: 4,
            ftm: 4,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '27',
            oreb: 1,
            pf: 0,
            player: {
                id: 666743,
                first_name: 'Terance',
                height_feet: null,
                height_inches: null,
                last_name: 'Mann',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 14,
            reb: 4,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 1,
        },
        {
            id: 13812084,
            ast: 2,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.25,
            fg3a: 4,
            fg3m: 1,
            fg_pct: 0.09090909,
            fga: 11,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '30',
            oreb: 2,
            pf: 4,
            player: {
                id: 666541,
                first_name: 'Luguentz',
                height_feet: null,
                height_inches: null,
                last_name: 'Dort',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 3,
            reb: 6,
            stl: 2,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 1,
        },
        {
            id: 13812085,
            ast: 4,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.5,
            fg3a: 4,
            fg3m: 2,
            fg_pct: 0.5833333,
            fga: 12,
            fgm: 7,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '32',
            oreb: 1,
            pf: 4,
            player: {
                id: 38017703,
                first_name: 'Jalen',
                height_feet: null,
                height_inches: null,
                last_name: 'Williams',
                position: 'G-F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 16,
            reb: 3,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 2,
        },
        {
            id: 13812086,
            ast: 4,
            blk: 0,
            dreb: 9,
            fg3_pct: 0.25,
            fg3a: 4,
            fg3m: 1,
            fg_pct: 0.42857143,
            fga: 7,
            fgm: 3,
            ft_pct: 0.5,
            fta: 2,
            ftm: 1,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '26',
            oreb: 0,
            pf: 2,
            player: {
                id: 38017706,
                first_name: 'Jaylin',
                height_feet: null,
                height_inches: null,
                last_name: 'Williams',
                position: 'F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 8,
            reb: 9,
            stl: 2,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 3,
        },
        {
            id: 13812080,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 172,
                first_name: 'Paul',
                height_feet: 6,
                height_inches: 9,
                last_name: 'George',
                position: 'F',
                team_id: 13,
                weight_pounds: 220,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812081,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 24417679,
                first_name: 'Xavier',
                height_feet: null,
                height_inches: null,
                last_name: 'Moon',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812082,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 380,
                first_name: 'Norman',
                height_feet: 6,
                height_inches: 4,
                last_name: 'Powell',
                position: 'F-G',
                team_id: 13,
                weight_pounds: 215,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812083,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896042,
                first_name: 'Jason',
                height_feet: null,
                height_inches: null,
                last_name: 'Preston',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812087,
            ast: 4,
            blk: 0,
            dreb: 0,
            fg3_pct: 0.4,
            fg3a: 5,
            fg3m: 2,
            fg_pct: 0.53333336,
            fga: 15,
            fgm: 8,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '26',
            oreb: 3,
            pf: 1,
            player: {
                id: 17896065,
                first_name: 'Josh',
                height_feet: null,
                height_inches: null,
                last_name: 'Giddey',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 18,
            reb: 3,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 2,
        },
        {
            id: 13812088,
            ast: 3,
            blk: 3,
            dreb: 4,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 0.6666667,
            fga: 15,
            fgm: 10,
            ft_pct: 1,
            fta: 9,
            ftm: 9,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '27',
            oreb: 0,
            pf: 2,
            player: {
                id: 175,
                first_name: 'Shai',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Gilgeous-Alexander',
                position: 'G',
                team_id: 21,
                weight_pounds: 181,
            },
            pts: 30,
            reb: 4,
            stl: 1,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 2,
        },
        {
            id: 13812089,
            ast: 1,
            blk: 0,
            dreb: 3,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 0.6666667,
            fga: 6,
            fgm: 4,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '16',
            oreb: 1,
            pf: 0,
            player: {
                id: 38017716,
                first_name: 'Ousmane',
                height_feet: null,
                height_inches: null,
                last_name: 'Dieng',
                position: 'F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 9,
            reb: 4,
            stl: 1,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 1,
        },
        {
            id: 13812090,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 4,
            fg3m: 0,
            fg_pct: 0,
            fga: 4,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '17',
            oreb: 0,
            pf: 1,
            player: {
                id: 3547272,
                first_name: 'Isaiah',
                height_feet: null,
                height_inches: null,
                last_name: 'Joe',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812091,
            ast: 2,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.25,
            fg3a: 4,
            fg3m: 1,
            fg_pct: 0.33333334,
            fga: 6,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '09',
            oreb: 1,
            pf: 0,
            player: {
                id: 17896036,
                first_name: 'Tre',
                height_feet: null,
                height_inches: null,
                last_name: 'Mann',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 5,
            reb: 2,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 2,
        },
        {
            id: 13812092,
            ast: 0,
            blk: 0,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.4,
            fga: 5,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '11',
            oreb: 3,
            pf: 0,
            player: {
                id: 17896021,
                first_name: 'Jeremiah',
                height_feet: null,
                height_inches: null,
                last_name: 'Robinson-Earl',
                position: 'F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 4,
            reb: 4,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812093,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '03',
            oreb: 0,
            pf: 0,
            player: {
                id: 407,
                first_name: 'Dario',
                height_feet: 6,
                height_inches: 10,
                last_name: 'Saric',
                position: 'F',
                team_id: 21,
                weight_pounds: 223,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812094,
            ast: 1,
            blk: 0,
            dreb: 1,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 1,
            fga: 1,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '08',
            oreb: 1,
            pf: 2,
            player: {
                id: 24572055,
                first_name: 'Olivier',
                height_feet: null,
                height_inches: null,
                last_name: 'Sarr',
                position: 'C',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 3,
            reb: 2,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812095,
            ast: 1,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.2857143,
            fg3a: 7,
            fg3m: 2,
            fg_pct: 0.2857143,
            fga: 7,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '22',
            oreb: 1,
            pf: 1,
            player: {
                id: 27924547,
                first_name: 'Lindy',
                height_feet: null,
                height_inches: null,
                last_name: 'Waters III',
                position: 'F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 6,
            reb: 2,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812096,
            ast: 0,
            blk: 0,
            dreb: 1,
            fg3_pct: 0.33333334,
            fg3a: 3,
            fg3m: 1,
            fg_pct: 0.25,
            fga: 4,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '13',
            oreb: 0,
            pf: 3,
            player: {
                id: 17896078,
                first_name: 'Aaron',
                height_feet: null,
                height_inches: null,
                last_name: 'Wiggins',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 3,
            reb: 1,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 1,
        },
        {
            id: 13812097,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 18677954,
                first_name: 'Jared',
                height_feet: null,
                height_inches: null,
                last_name: 'Butler',
                position: 'G',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812098,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017685,
                first_name: 'Chet',
                height_feet: null,
                height_inches: null,
                last_name: 'Holmgren',
                position: 'C-F',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812099,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547271,
                first_name: 'Aleksej',
                height_feet: null,
                height_inches: null,
                last_name: 'Pokusevski',
                position: 'C',
                team_id: 21,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812077,
            ast: 0,
            blk: 1,
            dreb: 7,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.5,
            fga: 2,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '24',
            oreb: 0,
            pf: 0,
            player: {
                id: 371,
                first_name: 'Mason',
                height_feet: 6,
                height_inches: 11,
                last_name: 'Plumlee',
                position: 'F-C',
                team_id: 13,
                weight_pounds: 235,
            },
            pts: 2,
            reb: 7,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 1,
        },
        {
            id: 13812073,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '05',
            oreb: 0,
            pf: 0,
            player: {
                id: 666511,
                first_name: 'Amir',
                height_feet: null,
                height_inches: null,
                last_name: 'Coffey',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812074,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 1,
            fga: 3,
            fgm: 3,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '04',
            oreb: 0,
            pf: 0,
            player: {
                id: 108,
                first_name: 'Robert',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Covington',
                position: 'F',
                team_id: 13,
                weight_pounds: 225,
            },
            pts: 7,
            reb: 0,
            stl: 1,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812078,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896022,
                first_name: 'Brandon',
                height_feet: null,
                height_inches: null,
                last_name: 'Boston Jr.',
                position: 'G',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812079,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017725,
                first_name: 'Moussa',
                height_feet: null,
                height_inches: null,
                last_name: 'Diabate',
                position: 'F',
                team_id: 13,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
        {
            id: 13812100,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 480,
                first_name: 'Kenrich',
                height_feet: 6,
                height_inches: 7,
                last_name: 'Williams',
                position: 'G-F',
                team_id: 21,
                weight_pounds: 210,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 21,
                abbreviation: 'OKC',
                city: 'Oklahoma City',
                conference: 'West',
                division: 'Northwest',
                full_name: 'Oklahoma City Thunder',
                name: 'Thunder',
            },
            turnover: 0,
        },
        {
            id: 13812072,
            ast: 3,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.6666667,
            fg3a: 6,
            fg3m: 4,
            fg_pct: 0.6666667,
            fga: 6,
            fgm: 4,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858449,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 13,
                home_team_score: 127,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 21,
                visitor_team_score: 105,
            },
            min: '19',
            oreb: 0,
            pf: 1,
            player: {
                id: 33,
                first_name: 'Nicolas',
                height_feet: 6,
                height_inches: 8,
                last_name: 'Batum',
                position: 'F-G',
                team_id: 13,
                weight_pounds: 200,
            },
            pts: 12,
            reb: 2,
            stl: 2,
            team: {
                id: 13,
                abbreviation: 'LAC',
                city: 'LA',
                conference: 'West',
                division: 'Pacific',
                full_name: 'LA Clippers',
                name: 'Clippers',
            },
            turnover: 0,
        },
    ],
};
