import { boxscoreDataType } from '../../types/basketballdata';

// Game ID 858448
export const game4: boxscoreDataType = {
    data: [
        {
            id: 13810695,
            ast: 1,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.5,
            fg3a: 8,
            fg3m: 4,
            fg_pct: 0.5,
            fga: 14,
            fgm: 7,
            ft_pct: 1,
            fta: 1,
            ftm: 1,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '33',
            oreb: 0,
            pf: 0,
            player: {
                id: 18677986,
                first_name: 'Trey',
                height_feet: null,
                height_inches: null,
                last_name: 'Murphy III',
                position: 'F',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 19,
            reb: 2,
            stl: 4,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 2,
        },
        {
            id: 13810696,
            ast: 10,
            blk: 0,
            dreb: 11,
            fg3_pct: 0.16666667,
            fg3a: 6,
            fg3m: 1,
            fg_pct: 0.4347826,
            fga: 23,
            fgm: 10,
            ft_pct: 1,
            fta: 9,
            ftm: 9,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '34',
            oreb: 0,
            pf: 3,
            player: {
                id: 227,
                first_name: 'Brandon',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Ingram',
                position: 'F',
                team_id: 19,
                weight_pounds: 190,
            },
            pts: 30,
            reb: 11,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810697,
            ast: 3,
            blk: 0,
            dreb: 11,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.625,
            fga: 16,
            fgm: 10,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '34',
            oreb: 8,
            pf: 2,
            player: {
                id: 455,
                first_name: 'Jonas',
                height_feet: 7,
                height_inches: 0,
                last_name: 'Valanciunas',
                position: 'C',
                team_id: 19,
                weight_pounds: 265,
            },
            pts: 20,
            reb: 19,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 3,
        },
        {
            id: 13810698,
            ast: 2,
            blk: 0,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 1,
            fg3m: 0,
            fg_pct: 0.2,
            fga: 5,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '29',
            oreb: 2,
            pf: 1,
            player: {
                id: 17896024,
                first_name: 'Herbert',
                height_feet: null,
                height_inches: null,
                last_name: 'Jones',
                position: 'F',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 2,
            reb: 3,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810699,
            ast: 3,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.375,
            fg3a: 8,
            fg3m: 3,
            fg_pct: 0.42105263,
            fga: 19,
            fgm: 8,
            ft_pct: 1,
            fta: 1,
            ftm: 1,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '36',
            oreb: 0,
            pf: 2,
            player: {
                id: 303,
                first_name: 'CJ',
                height_feet: 6,
                height_inches: 3,
                last_name: 'McCollum',
                position: 'G',
                team_id: 19,
                weight_pounds: 190,
            },
            pts: 20,
            reb: 2,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810700,
            ast: 1,
            blk: 0,
            dreb: 3,
            fg3_pct: 0,
            fg3a: 2,
            fg3m: 0,
            fg_pct: 0.25,
            fga: 4,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '12',
            oreb: 0,
            pf: 1,
            player: {
                id: 38017677,
                first_name: 'Dyson',
                height_feet: null,
                height_inches: null,
                last_name: 'Daniels',
                position: 'G',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 2,
            reb: 3,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 1,
        },
        {
            id: 13810701,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '02',
            oreb: 0,
            pf: 0,
            player: {
                id: 666626,
                first_name: 'Jaxson',
                height_feet: null,
                height_inches: null,
                last_name: 'Hayes',
                position: 'C',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810702,
            ast: 0,
            blk: 0,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 1,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '02',
            oreb: 0,
            pf: 2,
            player: {
                id: 207,
                first_name: 'Willy',
                height_feet: 6,
                height_inches: 11,
                last_name: 'Hernangomez',
                position: 'C',
                team_id: 19,
                weight_pounds: 240,
            },
            pts: 0,
            reb: 1,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 1,
        },
        {
            id: 13810703,
            ast: 1,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 2,
            fg3m: 0,
            fg_pct: 0,
            fga: 2,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '02',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547260,
                first_name: 'Kira',
                height_feet: null,
                height_inches: null,
                last_name: 'Lewis Jr.',
                position: 'G',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810704,
            ast: 3,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.33333334,
            fg3a: 3,
            fg3m: 1,
            fg_pct: 0.6,
            fga: 10,
            fgm: 6,
            ft_pct: 0.75,
            fta: 4,
            ftm: 3,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '21',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547293,
                first_name: 'Naji',
                height_feet: null,
                height_inches: null,
                last_name: 'Marshall',
                position: 'F',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 16,
            reb: 4,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 3,
        },
        {
            id: 13810705,
            ast: 0,
            blk: 0,
            dreb: 2,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '12',
            oreb: 0,
            pf: 1,
            player: {
                id: 340,
                first_name: 'Larry',
                height_feet: 6,
                height_inches: 9,
                last_name: 'Nance Jr.',
                position: 'F',
                team_id: 19,
                weight_pounds: 230,
            },
            pts: 0,
            reb: 2,
            stl: 1,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810706,
            ast: 2,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.5,
            fg3a: 2,
            fg3m: 1,
            fg_pct: 0.33333334,
            fga: 3,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '21',
            oreb: 1,
            pf: 2,
            player: {
                id: 391,
                first_name: 'Josh',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Richardson',
                position: 'G-F',
                team_id: 19,
                weight_pounds: 200,
            },
            pts: 3,
            reb: 5,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 1,
        },
        {
            id: 13810707,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 1,
            fg3a: 1,
            fg3m: 1,
            fg_pct: 1,
            fga: 1,
            fgm: 1,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '02',
            oreb: 0,
            pf: 0,
            player: {
                id: 436,
                first_name: 'Garrett',
                height_feet: 6,
                height_inches: 6,
                last_name: 'Temple',
                position: 'G-F',
                team_id: 19,
                weight_pounds: 195,
            },
            pts: 3,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810708,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896097,
                first_name: 'Jose',
                height_feet: null,
                height_inches: null,
                last_name: 'Alvarado',
                position: 'G',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810709,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017663,
                first_name: 'E.J.',
                height_feet: null,
                height_inches: null,
                last_name: 'Liddell',
                position: 'F',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810710,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017726,
                first_name: 'Dereon',
                height_feet: null,
                height_inches: null,
                last_name: 'Seabron',
                position: 'G',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810711,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666969,
                first_name: 'Zion',
                height_feet: null,
                height_inches: null,
                last_name: 'Williamson',
                position: 'F',
                team_id: 19,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 19,
                abbreviation: 'NOP',
                city: 'New Orleans',
                conference: 'West',
                division: 'Southwest',
                full_name: 'New Orleans Pelicans',
                name: 'Pelicans',
            },
            turnover: 0,
        },
        {
            id: 13810712,
            ast: 6,
            blk: 0,
            dreb: 3,
            fg3_pct: 0.2,
            fg3a: 5,
            fg3m: 1,
            fg_pct: 0.41666666,
            fga: 12,
            fgm: 5,
            ft_pct: 0.5,
            fta: 2,
            ftm: 1,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '30',
            oreb: 0,
            pf: 0,
            player: {
                id: 204,
                first_name: 'Gordon',
                height_feet: 6,
                height_inches: 8,
                last_name: 'Hayward',
                position: 'F',
                team_id: 4,
                weight_pounds: 225,
            },
            pts: 12,
            reb: 3,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 2,
        },
        {
            id: 13810713,
            ast: 2,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.2,
            fg3a: 10,
            fg3m: 2,
            fg_pct: 0.35,
            fga: 20,
            fgm: 7,
            ft_pct: 0.6666667,
            fta: 3,
            ftm: 2,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '35',
            oreb: 0,
            pf: 2,
            player: {
                id: 666950,
                first_name: 'P.J.',
                height_feet: null,
                height_inches: null,
                last_name: 'Washington',
                position: 'F',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 18,
            reb: 2,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 3,
        },
        {
            id: 13810714,
            ast: 1,
            blk: 0,
            dreb: 11,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.75,
            fga: 4,
            fgm: 3,
            ft_pct: 1,
            fta: 3,
            ftm: 3,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '30',
            oreb: 3,
            pf: 5,
            player: {
                id: 3547282,
                first_name: 'Nick',
                height_feet: null,
                height_inches: null,
                last_name: 'Richards',
                position: 'C',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 9,
            reb: 14,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 1,
        },
        {
            id: 13810715,
            ast: 2,
            blk: 0,
            dreb: 3,
            fg3_pct: 0,
            fg3a: 3,
            fg3m: 0,
            fg_pct: 0.4,
            fga: 10,
            fgm: 4,
            ft_pct: 0,
            fta: 1,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '12',
            oreb: 0,
            pf: 1,
            player: {
                id: 360,
                first_name: 'Kelly',
                height_feet: 6,
                height_inches: 7,
                last_name: 'Oubre Jr.',
                position: 'F',
                team_id: 4,
                weight_pounds: 205,
            },
            pts: 8,
            reb: 3,
            stl: 2,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 1,
        },
        {
            id: 13810716,
            ast: 2,
            blk: 0,
            dreb: 4,
            fg3_pct: 0.33333334,
            fg3a: 3,
            fg3m: 1,
            fg_pct: 0.5,
            fga: 4,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '10',
            oreb: 0,
            pf: 2,
            player: {
                id: 403,
                first_name: 'Terry',
                height_feet: 6,
                height_inches: 1,
                last_name: 'Rozier',
                position: 'G',
                team_id: 4,
                weight_pounds: 190,
            },
            pts: 5,
            reb: 4,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 1,
        },
        {
            id: 13810717,
            ast: 0,
            blk: 1,
            dreb: 4,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0.6666667,
            fga: 3,
            fgm: 2,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '20',
            oreb: 0,
            pf: 1,
            player: {
                id: 17896032,
                first_name: 'Kai',
                height_feet: null,
                height_inches: null,
                last_name: 'Jones',
                position: 'F-C',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 4,
            reb: 4,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
        {
            id: 13810718,
            ast: 6,
            blk: 1,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 3,
            fg3m: 0,
            fg_pct: 0.4,
            fga: 5,
            fgm: 2,
            ft_pct: 0.8,
            fta: 5,
            ftm: 4,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '25',
            oreb: 0,
            pf: 1,
            player: {
                id: 38017708,
                first_name: 'Bryce',
                height_feet: null,
                height_inches: null,
                last_name: 'McGowens',
                position: 'G',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 8,
            reb: 1,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 1,
        },
        {
            id: 13810719,
            ast: 1,
            blk: 0,
            dreb: 2,
            fg3_pct: 0.375,
            fg3a: 8,
            fg3m: 3,
            fg_pct: 0.5,
            fga: 12,
            fgm: 6,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '29',
            oreb: 0,
            pf: 1,
            player: {
                id: 338,
                first_name: 'Svi',
                height_feet: 6,
                height_inches: 8,
                last_name: 'Mykhailiuk',
                position: 'G',
                team_id: 4,
                weight_pounds: 205,
            },
            pts: 15,
            reb: 2,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 1,
        },
        {
            id: 13810720,
            ast: 4,
            blk: 0,
            dreb: 1,
            fg3_pct: 0,
            fg3a: 2,
            fg3m: 0,
            fg_pct: 0.5,
            fga: 8,
            fgm: 4,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '22',
            oreb: 1,
            pf: 1,
            player: {
                id: 421,
                first_name: 'Dennis',
                height_feet: 6,
                height_inches: 3,
                last_name: 'Smith Jr.',
                position: 'G',
                team_id: 4,
                weight_pounds: 195,
            },
            pts: 8,
            reb: 2,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 3,
        },
        {
            id: 13810721,
            ast: 0,
            blk: 2,
            dreb: 3,
            fg3_pct: 0.6666667,
            fg3a: 3,
            fg3m: 2,
            fg_pct: 0.6,
            fga: 5,
            fgm: 3,
            ft_pct: 0.5,
            fta: 2,
            ftm: 1,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '27',
            oreb: 0,
            pf: 3,
            player: {
                id: 18678001,
                first_name: 'JT',
                height_feet: null,
                height_inches: null,
                last_name: 'Thor',
                position: 'F',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 9,
            reb: 3,
            stl: 1,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 4,
        },
        {
            id: 13810722,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 38017698,
                first_name: 'Mark',
                height_feet: null,
                height_inches: null,
                last_name: 'Williams',
                position: 'C',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
        {
            id: 13810723,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547239,
                first_name: 'LaMelo',
                height_feet: null,
                height_inches: null,
                last_name: 'Ball',
                position: 'G',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
        {
            id: 13810724,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 17896037,
                first_name: 'James',
                height_feet: null,
                height_inches: null,
                last_name: 'Bouknight',
                position: 'G',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
        {
            id: 13810725,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 3547253,
                first_name: 'Theo',
                height_feet: null,
                height_inches: null,
                last_name: 'Maledon',
                position: 'G',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
        {
            id: 13810726,
            ast: 0,
            blk: 0,
            dreb: 0,
            fg3_pct: 0,
            fg3a: 0,
            fg3m: 0,
            fg_pct: 0,
            fga: 0,
            fgm: 0,
            ft_pct: 0,
            fta: 0,
            ftm: 0,
            game: {
                id: 858448,
                date: '2023-03-23T00:00:00.000Z',
                home_team_id: 19,
                home_team_score: 115,
                period: 4,
                postseason: false,
                season: 2022,
                status: 'Final',
                time: 'Final',
                visitor_team_id: 4,
                visitor_team_score: 96,
            },
            min: '00',
            oreb: 0,
            pf: 0,
            player: {
                id: 666748,
                first_name: 'Cody',
                height_feet: null,
                height_inches: null,
                last_name: 'Martin',
                position: 'F',
                team_id: 4,
                weight_pounds: null,
            },
            pts: 0,
            reb: 0,
            stl: 0,
            team: {
                id: 4,
                abbreviation: 'CHA',
                city: 'Charlotte',
                conference: 'East',
                division: 'Southeast',
                full_name: 'Charlotte Hornets',
                name: 'Hornets',
            },
            turnover: 0,
        },
    ],
};
