import * as NBAIcons from 'react-nba-logos';

const NBAIconsMap : {[abbrev: string]: JSX.Element} = {
    "ATL": <NBAIcons.ATL size="25"/>,
    "BKN": <NBAIcons.BKN size="25"/>,
    "BOS": <NBAIcons.BOS size="25"/>,
    "CHA": <NBAIcons.CHA size="25"/>,
    "CHI": <NBAIcons.CHI size="25"/>,
    "CLE": <NBAIcons.CLE size="25"/>,
    "DAL": <NBAIcons.DAL size="25"/>,
    "DEN": <NBAIcons.DEN size="25"/>,
    "DET": <NBAIcons.DET size="25"/>,
    "GSW": <NBAIcons.GSW size="25"/>,
    "HOU": <NBAIcons.HOU size="25"/>,
    "IND": <NBAIcons.IND size="25"/>,
    "LAC": <NBAIcons.LAC size="25"/>,
    "LAL": <NBAIcons.LAL size="25"/>,
    "MEM": <NBAIcons.MEM size="25"/>,
    "MIA": <NBAIcons.MIA size="25"/>,
    "MIL": <NBAIcons.MIL size="25"/>,
    "MIN": <NBAIcons.MIN size="25"/>,
    "NOP": <NBAIcons.NOP size="25"/>,
    "NYK": <NBAIcons.NYK size="25"/>,
    "OKC": <NBAIcons.OKC size="25"/>,
    "ORL": <NBAIcons.ORL size="25"/>,
    "PHI": <NBAIcons.PHI size="25"/>,
    "PHX": <NBAIcons.PHX size="25"/>,
    "POR": <NBAIcons.POR size="25"/>,
    "SAC": <NBAIcons.SAC size="25"/>,
    "SAS": <NBAIcons.SAS size="25"/>,
    "TOR": <NBAIcons.TOR size="25"/>,
    "UTA": <NBAIcons.UTA size="25"/>,
    "WAS": <NBAIcons.WAS size="25"/>,
}
export default NBAIconsMap
